# Generated by Django 3.2.6 on 2025-06-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='authority',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
