# Generated by Django 3.2.6 on 2025-06-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
