# Generated by Django 3.2.6 on 2025-06-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_exam', '0002_exam_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionset',
            old_name='exam_id',
            new_name='exam',
        ),
    ]
