# Generated by Django 3.2.6 on 2025-06-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=20, null=True)),
                ('number', models.CharField(max_length=20, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('college', models.CharField(max_length=50, null=True)),
                ('url', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
