# Generated by Django 3.2.6 on 2025-06-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0002_alter_student_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
