# Generated by Django 3.2.6 on 2025-06-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0003_alter_student_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user_id',
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
