# Generated by Django 3.2.6 on 2025-06-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('column_id', models.IntegerField(blank=True, null=True)),
                ('question_text', models.CharField(blank=True, max_length=200, null=True)),
                ('a', models.CharField(blank=True, max_length=200, null=True)),
                ('b', models.CharField(blank=True, max_length=200, null=True)),
                ('c', models.CharField(blank=True, max_length=200, null=True)),
                ('d', models.CharField(blank=True, max_length=200, null=True)),
                ('answer', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
